include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ignore_for_file: 
      - invalid_case_patterns
      - file_names


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
