name: volunteersapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  pretty_dio_logger: ^1.3.1
  http: ^1.2.1
  shared_preferences: ^2.2.0
  go_router: ^13.2.0

  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  html: ^0.15.4
  dio: ^5.4.2+1
  kafkabr: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  mockito: ^5.3.2
  bloc_test: ^9.1.4
  json_serializable: ^6.7.1

scripts:
  generate_mocks: flutter pub run build_runner build

flutter:
  generate: true
  uses-material-design: true

  assets:
    #- config_base64.json
    - assets/config.json