name: volunteersapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  pretty_dio_logger: ^1.3.1
  http: ^1.2.1
  shared_preferences: ^2.2.0
  go_router: ^13.2.0
  json_annotation: ^4.4.0


  intl: any
  provider: ^6.0.5
  html: ^0.15.4
  dio: ^5.4.2+1
  kafkabr: ^1.1.1
  flutter_esim: ^0.0.4
  sqflite: ^2.3.3+1
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  mockito: ^5.4.4
  bloc_test: ^9.1.4
  json_serializable: ^6.7.1

scripts:
  generate_mocks: flutter pub run build_runner build

flutter:
  generate: true
  uses-material-design: true

  assets:
    #- config_base64.json
    - assets/config.json
    - assets/images/background_image_drop.jpg
    - assets/images/background_image_black1.jpg
    - assets/images/background_image_brics.jpg
    - assets/images/family_400x400.jpg
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Sevillana
      fonts:
        - asset: assets/fonts/sevillana/Sevillana-Regular.ttf
          weight: 400
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Thin.ttf
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
    - family: MontSerrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-italic-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-SemiboldItalic.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-ThinItalic.ttf
    - family: Pangolin
      fonts:
        - asset: assets/fonts/pangolin/Pangolin-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-Black.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-BlackItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-ExtraBold.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-ExtraLight.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-ExtraLightItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-Light.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-Medium.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-MediumItalic.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-regular.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-Thin.ttf
        - asset: assets/fonts/roboto_condensed/static/RobotoCondensed-ThinItalic.ttf